# ============================================================
# CELL_6C — ARCHIMEDEAN / WEIL DICTIONARY AUDIT
#
# Purpose:
#
#   Cell 6A established that our direct S(r,x,L) agrees with
#   the repository's analytic S implementation.
#
#   Cell 6B established that the outer Archimedean quadrature
#   is not responsible for the discrepancy.
#
#   This cell therefore attacks the remaining dictionary:
#
#       repository source S(r,x,L)
#                |
#                v
#       divided-difference quadratic form
#                |
#                v
#       proposed Weil expression involving G_v(r)
#
# The central question is:
#
#   Does the repository's source/matrix construction actually
#   equal the Weil-side expression we have been using?
#
# We test this at the level of the integrand, before performing
# the expensive outer Archimedean integral.
#
# No changes to cell.py are required.
# ============================================================

import mpmath as mp

from cell import (
    DEFAULT_DPS,
    compute_L,
    canonical_to_full,
    normalise_ground_state,
    canonical_norm,
    G_complex,
)

from connes_cvs import (
    build_galerkin_matrix,
    compute_ground_state,
)


# ============================================================
# PARAMETERS
# ============================================================

mp.mp.dps = DEFAULT_DPS

c = 13
N = 8

# Use the same T as the earlier diagnostic cells, although
# this cell does not need to integrate all the way to T.
T = 40

dps = DEFAULT_DPS

L = compute_L(c)


print("\n" + "=" * 70)
print("CELL_6C — ARCHIMEDEAN / WEIL DICTIONARY AUDIT")
print("=" * 70)

print("\nParameters:")
print("c =", c)
print("N =", N)
print("T =", T)
print("dps =", dps)
print("L =", mp.nstr(L, 60))
print(
    "2*pi/L =",
    mp.nstr(2 * mp.pi / L, 60)
)


# ============================================================
# 1. GROUND STATE
# ============================================================

Q = build_galerkin_matrix(
    c=c,
    N=N,
    T=T,
    dps=dps,
)

lam_min, eigvec = compute_ground_state(Q)

v_star = normalise_ground_state(
    eigvec,
    N,
)

u_star = canonical_to_full(
    v_star,
    N,
)

print("\n" + "-" * 70)
print("1. GROUND STATE")
print("-" * 70)

print("\nlambda_min =")
print(mp.nstr(lam_min, 50))

print("\n||v_star|| =")
print(mp.nstr(
    canonical_norm(v_star),
    50
))

print("\n||u_star|| =")
print(mp.nstr(
    mp.sqrt(mp.fdot(u_star, u_star)),
    50
))


# ============================================================
# 2. DIRECT S(r,x,L)
#
# This is the source kernel used in the repository's
# Archimedean construction.
# ============================================================

def S_direct_cell6c(r, x):

    r = mp.mpf(r)
    x = mp.mpf(x)

    integrand = lambda y: (
        mp.sin(
            2 * mp.pi * x * (1 - y / L)
        )
        * mp.cos(r * y)
    )

    return mp.quad(
        integrand,
        [0, L]
    )


# ============================================================
# 3. THE SOURCE SUM FOR AN ARBITRARY VECTOR
#
# Since psi_arch(x) is linear in S(r,x,L), the quadratic
# form generated by the divided differences can be written
# directly in terms of S.
#
# Define
#
#   D_v(r) =
#       sum_{m,n} u_m u_n D_S(m,n;r)
#
# where
#
#   D_S(m,n;r)
#      = [S(r,m)-S(r,n)]/(m-n),  m != n
#
#   D_S(n,n;r)
#      = dS/dx(r,n).
#
# This is the source-level integrand of the repository
# Archimedean quadratic form.
# ============================================================

def dS_direct_cell6c(r, x):

    r = mp.mpf(r)
    x = mp.mpf(x)

    integrand = lambda y: (
        2 * mp.pi
        * (1 - y / L)
        * mp.cos(
            2 * mp.pi * x * (1 - y / L)
        )
        * mp.cos(r * y)
    )

    return mp.quad(
        integrand,
        [0, L]
    )


def source_divdiff_kernel_cell6c(
    r,
    m,
    n,
):

    if m != n:

        return (
            S_direct_cell6c(r, m)
            - S_direct_cell6c(r, n)
        ) / mp.mpf(m - n)

    return dS_direct_cell6c(r, m)


def source_quadratic_integrand_cell6c(r):

    r = mp.mpf(r)

    total = mp.mpf(0)

    for i, m in enumerate(
        range(-N, N + 1)
    ):

        for j, n in enumerate(
            range(-N, N + 1)
        ):

            total += (
                u_star[i]
                * u_star[j]
                * source_divdiff_kernel_cell6c(
                    r,
                    m,
                    n,
                )
            )

    return total


# ============================================================
# 4. DIRECT WEIL-SIDE INTEGRAND
#
# This is the expression previously used:
#
#   Re G_v(r)
#
# The proposed Archimedean quadratic form was
#
#   1/pi int_0^T h_+(r) Re G_v(r) dr.
#
# Before including h_+(r), compare the underlying response
# directly.
# ============================================================

def weil_response_cell6c(r):

    return mp.re(
        G_complex(
            v_star,
            r,
            L,
        )
    )


# ============================================================
# 5. TEST POINTS
#
# Include generic points and points near the Fourier
# frequencies 2*pi*k/L.
# ============================================================

test_r_values = [
    mp.mpf("0"),
    mp.mpf("0.5"),
    mp.mpf("1.0"),
    mp.mpf("1.5"),
    mp.mpf("2.0"),
    mp.mpf("2.4496332798546520107426711685"),
    mp.mpf("3.0"),
    mp.mpf("5.0"),
    mp.mpf("7.5"),
    mp.mpf("10.0"),
    mp.mpf("15.0"),
    mp.mpf("20.0"),
]


print("\n" + "-" * 70)
print("2. SOURCE-LEVEL RESPONSE COMPARISON")
print("-" * 70)

print(
    "\nFor each r we compare:"
)
print(
    "  D_source(r) = quadratic-form kernel generated from S"
)
print(
    "  G_response(r) = Re G_v(r)"
)

print(
    "\nIf the dictionary is correct, these should have a"
)
print(
    "precisely identifiable relationship, potentially involving"
)
print(
    "a constant factor, sign, or an additional simple term."
)


response_data = []

for r in test_r_values:

    d_source = source_quadratic_integrand_cell6c(r)

    g_response = weil_response_cell6c(r)

    response_data.append(
        (
            r,
            d_source,
            g_response,
        )
    )

    print("\nr =")
    print(mp.nstr(r, 35))

    print("  D_source(r) =")
    print(mp.nstr(d_source, 50))

    print("  Re G_v(r) =")
    print(mp.nstr(g_response, 50))

    if abs(g_response) > mp.mpf("1e-40"):

        print("  ratio D_source / Re(G) =")
        print(
            mp.nstr(
                d_source / g_response,
                50
            )
        )

    else:

        print(
            "  ratio unavailable: Re(G) is numerically tiny"
        )


# ============================================================
# 6. TEST WHETHER D_source IS PROPORTIONAL TO G
#
# Find the ratios where G is not tiny.
#
# This is diagnostic only; we do NOT fit a correction.
# ============================================================

print("\n" + "-" * 70)
print("3. RATIO STABILITY")
print("-" * 70)

ratios = []

for r, d_source, g_response in response_data:

    if abs(g_response) > mp.mpf("1e-20"):

        ratio = d_source / g_response

        ratios.append(
            (
                r,
                ratio
            )
        )

        print(
            "r =",
            mp.nstr(r, 25),
            " ratio =",
            mp.nstr(ratio, 50)
        )


if ratios:

    ratio_min = min(
        ratio
        for r, ratio in ratios
    )

    ratio_max = max(
        ratio
        for r, ratio in ratios
    )

    print("\nMinimum ratio =")
    print(mp.nstr(ratio_min, 50))

    print("\nMaximum ratio =")
    print(mp.nstr(ratio_max, 50))

    print("\nRatio spread =")
    print(
        mp.nstr(
            ratio_max - ratio_min,
            50
        )
    )


# ============================================================
# 7. TEST SIMPLE CONSTANTS
#
# Compare D_source / G against likely normalization factors.
#
# We deliberately report rather than assume.
# ============================================================

candidate_factors = [
    ("1", mp.mpf(1)),
    ("2", mp.mpf(2)),
    ("1/2", mp.mpf("0.5")),
    ("pi", mp.pi),
    ("1/pi", 1 / mp.pi),
    ("2*pi", 2 * mp.pi),
    ("1/(2*pi)", 1 / (2 * mp.pi)),
    ("4*pi", 4 * mp.pi),
    ("1/(4*pi)", 1 / (4 * mp.pi)),
    ("pi^2", mp.pi**2),
    ("1/pi^2", 1 / mp.pi**2),
]


print("\n" + "-" * 70)
print("4. SIMPLE NORMALISATION TESTS")
print("-" * 70)

for name, factor in candidate_factors:

    maximum_error = mp.mpf(0)

    for r, d_source, g_response in response_data:

        if abs(g_response) > mp.mpf("1e-20"):

            error = abs(
                d_source
                - factor * g_response
            )

            if error > maximum_error:

                maximum_error = error

    print(
        f"\nD_source - ({name}) Re(G):"
    )

    print(
        mp.nstr(
            maximum_error,
            50
        )
    )


# ============================================================
# 8. BASIS-BY-BASIS TEST
#
# The ground state could in principle hide structure through
# cancellation. Therefore repeat the comparison for individual
# canonical basis vectors.
#
# This is particularly important.
# ============================================================

print("\n" + "-" * 70)
print("5. BASIS-BY-BASIS DICTIONARY TEST")
print("-" * 70)

basis_test_r = [
    mp.mpf("0.5"),
    mp.mpf("1.0"),
    mp.mpf("2.0"),
    mp.mpf("3.0"),
    mp.mpf("5.0"),
]


def basis_vector_full_cell6c(k):

    v = [
        mp.mpf(0)
        for _ in range(N + 1)
    ]

    v[k] = mp.mpf(1)

    return canonical_to_full(
        v,
        N,
    )


def source_quadratic_for_basis_cell6c(
    r,
    k,
):

    u = basis_vector_full_cell6c(k)

    total = mp.mpf(0)

    for i, m in enumerate(
        range(-N, N + 1)
    ):

        for j, n in enumerate(
            range(-N, N + 1)
        ):

            total += (
                u[i]
                * u[j]
                * source_divdiff_kernel_cell6c(
                    r,
                    m,
                    n,
                )
            )

    return total


def G_basis_response_cell6c(
    r,
    k,
):

    v = [
        mp.mpf(0)
        for _ in range(N + 1)
    ]

    v[k] = mp.mpf(1)

    return mp.re(
        G_complex(
            v,
            r,
            L,
        )
    )


for k in range(0, N + 1):

    print("\nCanonical basis k =", k)

    for r in basis_test_r:

        d_source = (
            source_quadratic_for_basis_cell6c(
                r,
                k,
            )
        )

        g_basis = (
            G_basis_response_cell6c(
                r,
                k,
            )
        )

        print(
            "  r =",
            mp.nstr(r, 15),
            " D_source =",
            mp.nstr(d_source, 30),
            " Re(G_k) =",
            mp.nstr(g_basis, 30)
        )

        if abs(g_basis) > mp.mpf("1e-20"):

            print(
                "       ratio =",
                mp.nstr(
                    d_source / g_basis,
                    30
                )
            )


# ============================================================
# 9. IMPORTANT: TEST THE SUMMED KERNEL IDENTITY
#
# There is a useful algebraic identity here.
#
# For a scalar function f(x), define
#
#   D_f(m,n) =
#       (f(m)-f(n))/(m-n)
#
# with the derivative on the diagonal.
#
# For symmetric coefficients u_m u_n, the quadratic form
#
#   sum_mn u_m u_n D_f(m,n)
#
# can be rewritten as a divided-difference expression.
#
# We compare the direct double sum with an independently
# assembled matrix product to ensure there is no hidden
# indexing/canonical-coordinate issue in our source kernel.
# ============================================================

print("\n" + "-" * 70)
print("6. INTERNAL SOURCE QUADRATIC-FORM CONSISTENCY")
print("-" * 70)


def build_source_kernel_matrix_cell6c(r):

    size = 2 * N + 1

    M = mp.matrix(
        size,
        size
    )

    for i, m in enumerate(
        range(-N, N + 1)
    ):

        for j, n in enumerate(
            range(-N, N + 1)
        ):

            M[i, j] = (
                source_divdiff_kernel_cell6c(
                    r,
                    m,
                    n,
                )
            )

    return M


for r in [
    mp.mpf("1"),
    mp.mpf("2"),
    mp.mpf("5"),
]:

    M = build_source_kernel_matrix_cell6c(r)

    direct = source_quadratic_integrand_cell6c(r)

    matrix_form = mp.fdot(
        u_star,
        M * u_star
    )

    print("\nr =")
    print(mp.nstr(r, 30))

    print("  direct double sum =")
    print(mp.nstr(direct, 50))

    print("  matrix quadratic form =")
    print(mp.nstr(matrix_form, 50))

    print("  difference =")
    print(
        mp.nstr(
            direct - matrix_form,
            50
        )
    )


# ============================================================
# 10. FINAL DIAGNOSTIC
# ============================================================

print("\n" + "=" * 70)
print("CELL_6C SUMMARY")
print("=" * 70)

print("""
Cell 6C does NOT attempt to explain the discrepancy by fitting
a correction factor.

It asks a more fundamental question:

    What is the exact pointwise relationship between the
    repository source kernel and Re G_v(r)?

The important outputs are:

  * D_source(r)
  * Re G_v(r)
  * their ratios
  * basis-by-basis ratios
  * tests against simple constants

Interpretation:

  1. If the ratio is constant, we have likely found a
     normalization factor.

  2. If the ratio is not constant, the difference is not
     merely a scalar normalization.

  3. If the basis-by-basis behaviour differs from the
     ground-state behaviour, cancellation in the ground
     state was hiding the underlying structure.

  4. The internal matrix check should remain at essentially
     machine-independent high precision. If it does not,
     there is an indexing or construction problem in this
     diagnostic itself.
""")

print("\n" + "=" * 70)
print("END CELL_6C")
print("=" * 70)
